# Generated by Django 4.2.3 on 2023-09-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libraries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone_num', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('leader', models.CharField(max_length=255)),
            ],
        ),
    ]
